### ISSUE TITLE
好东西啊

### ISSUE THREAD

**Issue by aDon0000** [lyscop/Strokesplus.Net-Scripts#1]
四角和边缘那两个是最实用的，但是边缘的为啥不列出来啊，直接覆盖我怕冲坏我之前的，懒得搞来搞去

**Comment by aDon0000** [comment]
另外，截图到屏幕 调用自带截图 那个，双击无法关闭屏幕截图

**Comment by aDon0000** [comment]
搞定了。。。原来双击关闭被注释掉了。。。

**Comment by lyscop** [comment]
感谢支持和反馈

边缘是类似MouseInc的屏幕边缘滚动吗？

**Comment by aDon0000** [comment]
19 屏幕边缘滚动调节亮度、声音、浏览器标签页切换、程序切换
就是这个，已看就是实用的好东西，能不能把代码列出来呢。我在小众看到过来的

**Comment by lyscop** [comment]
嗯，稍等

**Comment by aDon0000** [comment]
OK，期待，谢谢大佬

**Comment by lyscop** [comment]
更新了，原默认的滚动代码可以注释存着，不覆盖

要是设置了一些软件里面滚动动作，可以再添加到新的里面来

**Comment by aDon0000** [comment]
用上啦！舒服！谢谢啦
