### ISSUE TITLE
请问下您能分享下您的鼠标快捷键的布置吗？

### ISSUE THREAD

**Issue by LoyaltyMu** [lyscop/Strokesplus.Net-Scripts#2]
请问下您能分享下您的鼠标快捷键的布置吗？比如桌面手势打开摸个软件这样

**Comment by lyscop** [comment]
手势图发在小众软件了，说明里面点开查看

**Comment by LoyaltyMu** [comment]
> 手势图发在小众软件了，说明里面点开查看
嗯嗯  看到了 但是设置对小白来说太复杂了   考虑以后会分享这个手势设置配置吗

**Comment by lyscop** [comment]
分享的功能添加了部分在配置里面，也是发在小众

想了解下是如何选择使用这一个手势软件的呢
