### ISSUE TITLE
划词翻译bug

### ISSUE THREAD

**Issue by qstdnx** [lyscop/Strokesplus.Net-Scripts#9]
1划词翻译弹出的中文文本框有限，如果复制大段文字翻译会出现只翻译一小部分的问题。
![image](https://github.com/lyscop/Strokesplus.Net-Scripts/assets/20844622/e513a669-e480-4dbb-8684-6d60fa197d9e)
但是这个问题在中翻英的时候又没有
![image](https://github.com/lyscop/Strokesplus.Net-Scripts/assets/20844622/d7bfb908-bccd-4ec3-8d48-33ef28e0ff88)

2翻译框里的中文分段也有点奇怪，不过貌似不影响翻译结果

3如果翻译的大段文字中只要出现一个中文，那么就会变成中翻英。
![image](https://github.com/lyscop/Strokesplus.Net-Scripts/assets/20844622/3a33337d-6c07-4d27-bdaf-0140ab84cc3d)

**Comment by lyscop** [comment]
因为用了弹窗显示的方式，供方便阅读，不建议翻译大段文字，要是有其他需要可以使用网页或者程序翻译工具，以及整页翻译
